### ISSUE TITLE
Brand error in PriceWaiterConfig

### ISSUE THREAD

**Issue by taeo** [pricewaiter/magento#16]
@bobbyburden
`SyntaxError: expected expression, got ','` in `brand: ,`

```js
product: {
  brand: ,
  # Other options not shown
}
```

**Comment by DirkUnk** [comment]
@bobbyburden Please notify me when this is resolved.

**Comment by bobbyburden** [comment]
@DirkUnk This is fixed, and has been submitted to Magento Connect.
